services:
  user_api:
    build: ./patient-services
    container_name: user_services
    ports:
      - "3000:8080"
    env_file:
      - ./patient-services/.env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:8.2.3-noble
    container_name: mongo_db
    command: ["mongod", "--port", "27018"]
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo_express
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27018
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
